### ISSUE TITLE
‘scorecard’ version 0.3.2

### ISSUE THREAD

**Issue by fangxingouyang** [ShichenXie/scorecard#49] opened 2021-05-01 14:32 UTC
describe(data)

Error in setnames(sum_dtnum, c("min", "p25", "p50", "mean", "p75", "max",  : 
  Can't assign 8 names to a 9 column data.table
In addition: Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)

and it causes many other problems of scorecard package funtions

**Comment by ShichenXie** [comment] 2021-05-05 13:08
I can't reproduce your issue. Please provide more information, such as your codes and the `sessionInfo()` results.

**Comment by ShichenXie** [comment] 2021-05-09 01:11
I close this issue new, since I still cant reproduce it. If you have more information, you can open it again.

**Comment by fangxingouyang** [comment] 2021-05-10 07:07
Dear Dr XIE：
&nbsp; &nbsp; &nbsp; data_xw is a normal dataframe, so I do believe there is a bug in&nbsp;scorecard::describe function.
&nbsp; &nbsp; &nbsp; &nbsp; best regrads




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShichenXie/scorecard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月9日(星期天) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShichenXie/scorecard] ‘scorecard’ version 0.3.2 (#49)





 
I close this issue new, since I still cant reproduce it. If you have more information, you can open it again.

**Comment by ShichenXie** [comment] 2021-05-10 09:30
我这边复现不了你的问题。你可以重新安装之后再试试。无法复现就没法定位。

**Comment by fangxingouyang** [comment] 2021-06-04 11:50
谢博士好：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 今天才有空复盘，这个问题很简单：


scorecard::describe
function (dt)&nbsp;
{
&nbsp; &nbsp; dt = setDT(copy(dt))


&nbsp; &nbsp; sum_dt = data.table(variable = names(dt), class = dt[, sapply(.SD,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; class)], count = dt[, .N], unique_count = dt[, sapply(.SD,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; function(x) uniqueN(x, na.rm = TRUE))], identical_rate = dt[,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; sapply(.SD, function(a) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pt = prop.table(table(a))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; max_rate = ifelse(length(pt) == 0, Inf, max(pt, na.rm = TRUE))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return(max_rate)
&nbsp; &nbsp; &nbsp; &nbsp; })], missing_rate = dt[, sapply(.SD, function(x) mean(is.na(x)))])
&nbsp; &nbsp; xnum = names(which(dt[, sapply(.SD, is.numeric)]))


&nbsp; &nbsp; dtnum = dt[, xnum, with = FALSE]


&nbsp; &nbsp; sum_dtnum = as.data.table(do.call(rbind, lapply(dtnum, summary)))[,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; `:=`(variable = xnum, sd = dtnum[, sapply(.SD,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sd)])]


&nbsp; &nbsp; setnames(sum_dtnum, c("min", "p25", "p50",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "mean", "p75", "max", "variable",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "sd"))
&nbsp; &nbsp; sum_dtnum = sum_dtnum[, c("variable", "mean",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "sd", "min", "p25", "p50", "p75",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "max"), with = FALSE]
&nbsp; &nbsp; vardesc = merge(sum_dt, sum_dtnum, by = "variable",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; all = TRUE, sort = FALSE)[, `:=`((c("identical_rate",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "missing_rate", "mean", "sd")), lapply(.SD,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; function(x) round(x, 4))), .SDcols = c("identical_rate",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; "missing_rate", "mean", "sd")][]
&nbsp; &nbsp; return(vardesc)
}





问题出在：







下面这一句的summary里面实际建模中肯定有很多&nbsp;NA's的情况，一共9列。


sum_dtnum = as.data.table(do.call(rbind, lapply(dtnum, summary)))[,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; `:=`(variable = xnum, sd = dtnum[, sapply(.SD,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sd)])]



而下一句


setnames(sum_dtnum, c("min", "p25", "p50", "mean", "p75", "max", "variable", "sd"))



只给八个列赋名：



所以一发动全身，导致report函数也不能使用了。


我R语言一般，不太会去包里修改，麻烦您和您的团队尽快发布新的版本。


谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShichenXie/scorecard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShichenXie/scorecard] ‘scorecard’ version 0.3.2 (#49)





 
我这边复现不了你的问题。你可以重新安装之后再试试。无法复现就没法定位。

**Comment by ShichenXie** [comment] 2021-06-06 02:33
你自己登陆本网页看看，完全看不懂你在说啥，之间有很多乱码。你只需要给两列出现问题的数据以及对应的代码就可以了。

**Comment by fangxingouyang** [comment] 2021-06-06 06:23
scorecard::describe
函数里面这句：忽略了对缺失值的处理
setnames(sum_dtnum, c("min", "p25", "p50", "mean", "p75", "max", "variable", "sd"))









------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ShichenXie/scorecard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShichenXie/scorecard] ‘scorecard’ version 0.3.2 (#49)





 
你自己登陆本网页看看，完全看不懂你在说啥，之间有很多乱码。你只需要给两列出现问题的数据以及对应的代码就可以了。

**Comment by ShichenXie** [comment] 2021-06-06 10:29
这个bug应该解决了，请通过`devtools::install_github("shichenxie/scorecard")`安装github上面的最新版本试试看。

**Closed as completed** 2021-06-11 13:09 UTC
