### ISSUE TITLE
Issue with the counts in the woebin results

### ISSUE THREAD

**Issue by jm448** [ShichenXie/scorecard#50] opened 2021-05-20 00:21 UTC
Hi @ShichenXie,
I have the following question regarding the counts and the cut points of the variables. In this example, replicating the record count for variable “x” using the base :: cut function does not get the same results as with the woebin function.
Also, I have verified that when using the woebin_ply function, the counts match the base :: cut calculation.
Thank you,

``` r

library(readr)
library(scorecard)
#> Warning: package 'scorecard' was built under R version 4.0.5
suppressPackageStartupMessages(library(dplyr))

packageVersion("scorecard")
#> [1] '0.3.2'

d <- read_csv("https://gist.githubusercontent.com/jm448/a8edc0f3a89c6797c52aa84f978eca6f/raw/4ca39c576a23ae5b94b19c5829149d6800b75991/data.txt")
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   x = col_double(),
#>   response = col_double()
#> )

glimpse(d)
#> Rows: 253
#> Columns: 2
#> $ x        <dbl> 1.0000000, -999.0000000, 0.3639344, 0.9988413, 0.7696078, ...
#> $ response <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...

bin <- woebin(
  d, 
  x = "x",
  y = "response",
  method = "tree",
  count_distr_limit = 0.05 
)
#> [INFO] creating woe binning ...

bin
#> $x
#>    variable        bin count count_distr neg pos    posprob         woe
#> 1:        x   [-Inf,0)    24  0.09486166  15   9 0.37500000  1.16158709
#> 2:        x   [0,0.52)    88  0.34782609  80   8 0.09090909 -0.63017238
#> 3:        x [0.52,0.6)    21  0.08300395  16   5 0.23809524  0.50926190
#> 4:        x [0.6, Inf)   120  0.47430830 102  18 0.15000000 -0.06218834
#>         bin_iv  total_iv breaks is_special_values
#> 1: 0.179555187 0.3174041      0             FALSE
#> 2: 0.110649986 0.3174041   0.52             FALSE
#> 3: 0.025403323 0.3174041    0.6             FALSE
#> 4: 0.001795579 0.3174041    Inf             FALSE

# counts:

bin$x$count
#> [1]  24  88  21 120

brks <- bin$x$breaks
brks <- as.numeric(brks)
brks <- c(-Inf, brks)

brks
#> [1] -Inf 0.00 0.52 0.60  Inf

dc <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin)

dc
#> # A tibble: 4 x 2
#>   x_bin          n
#>   <fct>      <int>
#> 1 [-Inf,0)      24
#> 2 [0,0.52)      88
#> 3 [0.52,0.6)    20
#> 4 [0.6, Inf)   121

# the counts using cut doesn't match with the woebin results  

dc$n
#> [1]  24  88  20 121

# the counts match using woebin_ply

woebin_ply(d, bins = bin, to = "bin") %>%
  as_tibble() %>% 
  mutate(
    x = d$x,
    x_bin2 = cut(x, brks, right = FALSE)
  ) %>% 
  filter(x_bin != x_bin2)
#> [INFO] converting into woe values ...
#> # A tibble: 0 x 4
#> # ... with 4 variables: response <dbl>, x_bin <chr>, x <dbl>, x_bin2 <fct>

# the woe values match

bin$x %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(bin, count, pos, neg, woe, woe2) %>% 
  mutate(woe == woe2)
#>           bin count pos neg         woe        woe2 woe == woe2
#> 1:   [-Inf,0)    24   9  15  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52)    88   8  80 -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)    21   5  16  0.50926190  0.50926190        TRUE
#> 4: [0.6, Inf)   120  18 102 -0.06218834 -0.06218834        TRUE

# woe values using base::cut

bin2 <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin, response) %>% 
  mutate(response = if_else(response == 1, "pos", "neg")) %>% 
  tidyr::pivot_wider(names_from = "response", values_from = "n") %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(x_bin, woe2)
  
# the woe values using base::cut doesn't match with woe values from woebin

bin$x %>% 
  select(bin, woe) %>% 
  left_join(bin2, by = c("bin" = "x_bin")) %>% 
  mutate(woe == woe2)
#>           bin         woe        woe2 woe == woe2
#> 1:   [-Inf,0)  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52) -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)  0.50926190  0.57380042       FALSE
#> 4: [0.6, Inf) -0.06218834 -0.07194452       FALSE
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ShichenXie** [comment] 2021-05-20 12:58
That's strange. I have run your codes on both Mac and Ubuntu, the results of which are as following. The function woebin and base's cut functions have the same results.  Actually, woebin function also uses base's cut to get bins. 


``` r
library(readr)
library(scorecard)
#> Warning: package 'scorecard' was built under R version 4.0.5
suppressPackageStartupMessages(library(dplyr))

packageVersion("scorecard")
#> [1] '0.3.2'
#> [1] '0.3.2'

d <- read_csv("https://gist.githubusercontent.com/jm448/a8edc0f3a89c6797c52aa84f978eca6f/raw/4ca39c576a23ae5b94b19c5829149d6800b75991/data.txt")
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   x = col_double(),
#>   response = col_double()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   x = col_double(),
#>   response = col_double()
#> )

glimpse(d)
#> Rows: 253
#> Columns: 2
#> $ x        <dbl> 1.0000000, -999.0000000, 0.3639344, 0.9988413, 0.7696078, 0.8…
#> $ response <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1…
#> Rows: 253
#> Columns: 2
#> $ x        <dbl> 1.0000000, -999.0000000, 0.3639344, 0.9988413, 0.7696078, ...
#> $ response <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...

bin <- woebin(
  d, 
  x = "x",
  y = "response",
  method = "tree",
  count_distr_limit = 0.05 
)
#> [INFO] creating woe binning ...
#> [INFO] creating woe binning ...

bin
#> $x
#>    variable         bin count count_distr neg pos    posprob         woe
#> 1:        x    [-Inf,0)    24  0.09486166  15   9 0.37500000  1.16158709
#> 2:        x    [0,0.02)    16  0.06324111  13   3 0.18750000  0.20607564
#> 3:        x [0.02,0.28)    31  0.12252964  30   1 0.03225806 -1.72878467
#> 4:        x [0.28,0.52)    41  0.16205534  37   4 0.09756098 -0.55221084
#> 5:        x  [0.52,0.6)    20  0.07905138  15   5 0.25000000  0.57380042
#> 6:        x  [0.6, Inf)   121  0.47826087 103  18 0.14876033 -0.07194452
#>         bin_iv  total_iv breaks is_special_values
#> 1: 0.179555187 0.4571391      0             FALSE
#> 2: 0.002878287 0.4571391   0.02             FALSE
#> 3: 0.200271182 0.4571391   0.28             FALSE
#> 4: 0.040702865 0.4571391   0.52             FALSE
#> 5: 0.031316572 0.4571391    0.6             FALSE
#> 6: 0.002415039 0.4571391    Inf             FALSE
#> $x
#>    variable        bin count count_distr neg pos    posprob         woe
#> 1:        x   [-Inf,0)    24  0.09486166  15   9 0.37500000  1.16158709
#> 2:        x   [0,0.52)    88  0.34782609  80   8 0.09090909 -0.63017238
#> 3:        x [0.52,0.6)    21  0.08300395  16   5 0.23809524  0.50926190
#> 4:        x [0.6, Inf)   120  0.47430830 102  18 0.15000000 -0.06218834
#>         bin_iv  total_iv breaks is_special_values
#> 1: 0.179555187 0.3174041      0             FALSE
#> 2: 0.110649986 0.3174041   0.52             FALSE
#> 3: 0.025403323 0.3174041    0.6             FALSE
#> 4: 0.001795579 0.3174041    Inf             FALSE

# counts:

bin$x$count
#> [1]  24  16  31  41  20 121
#> [1]  24  88  21 120

brks <- bin$x$breaks
brks <- as.numeric(brks)
brks <- c(-Inf, brks)

brks
#> [1] -Inf 0.00 0.02 0.28 0.52 0.60  Inf
#> [1] -Inf 0.00 0.52 0.60  Inf

dc <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin)

dc
#> # A tibble: 6 x 2
#>   x_bin           n
#> * <fct>       <int>
#> 1 [-Inf,0)       24
#> 2 [0,0.02)       16
#> 3 [0.02,0.28)    31
#> 4 [0.28,0.52)    41
#> 5 [0.52,0.6)     20
#> 6 [0.6, Inf)    121
#> # A tibble: 4 x 2
#>   x_bin          n
#>   <fct>      <int>
#> 1 [-Inf,0)      24
#> 2 [0,0.52)      88
#> 3 [0.52,0.6)    20
#> 4 [0.6, Inf)   121

# the counts using cut doesn't match with the woebin results  

dc$n
#> [1]  24  16  31  41  20 121
#> [1]  24  88  20 121

# the counts match using woebin_ply

woebin_ply(d, bins = bin, to = "bin") %>%
  as_tibble() %>% 
  mutate(
    x = d$x,
    x_bin2 = cut(x, brks, right = FALSE)
  ) %>% 
  filter(x_bin != x_bin2)
#> [INFO] converting into woe values ...
#> # A tibble: 0 x 4
#> # … with 4 variables: response <dbl>, x_bin <chr>, x <dbl>, x_bin2 <fct>
#> [INFO] converting into woe values ...
#> # A tibble: 0 x 4
#> # ... with 4 variables: response <dbl>, x_bin <chr>, x <dbl>, x_bin2 <fct>

# the woe values match

bin$x %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(bin, count, pos, neg, woe, woe2) %>% 
  mutate(woe == woe2)
#>            bin count pos neg         woe        woe2 woe == woe2
#> 1:    [-Inf,0)    24   9  15  1.16158709  1.16158709        TRUE
#> 2:    [0,0.02)    16   3  13  0.20607564  0.20607564        TRUE
#> 3: [0.02,0.28)    31   1  30 -1.72878467 -1.72878467        TRUE
#> 4: [0.28,0.52)    41   4  37 -0.55221084 -0.55221084        TRUE
#> 5:  [0.52,0.6)    20   5  15  0.57380042  0.57380042        TRUE
#> 6:  [0.6, Inf)   121  18 103 -0.07194452 -0.07194452        TRUE
#>           bin count pos neg         woe        woe2 woe == woe2
#> 1:   [-Inf,0)    24   9  15  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52)    88   8  80 -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)    21   5  16  0.50926190  0.50926190        TRUE
#> 4: [0.6, Inf)   120  18 102 -0.06218834 -0.06218834        TRUE

# woe values using base::cut

bin2 <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin, response) %>% 
  mutate(response = if_else(response == 1, "pos", "neg")) %>% 
  tidyr::pivot_wider(names_from = "response", values_from = "n") %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(x_bin, woe2)

# the woe values using base::cut doesn't match with woe values from woebin

bin$x %>% 
  select(bin, woe) %>% 
  left_join(bin2, by = c("bin" = "x_bin")) %>% 
  mutate(woe == woe2)
#>            bin         woe        woe2 woe == woe2
#> 1:    [-Inf,0)  1.16158709  1.16158709        TRUE
#> 2:    [0,0.02)  0.20607564  0.20607564        TRUE
#> 3: [0.02,0.28) -1.72878467 -1.72878467        TRUE
#> 4: [0.28,0.52) -0.55221084 -0.55221084        TRUE
#> 5:  [0.52,0.6)  0.57380042  0.57380042        TRUE
#> 6:  [0.6, Inf) -0.07194452 -0.07194452        TRUE
#>           bin         woe        woe2 woe == woe2
#> 1:   [-Inf,0)  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52) -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)  0.50926190  0.57380042       FALSE
#> 4: [0.6, Inf) -0.06218834 -0.07194452       FALSE
```

<sup>Created on 2021-05-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ShichenXie** [comment] 2021-05-23 14:36
I'm close this issue now, since I can't reproduce it. If you have more information, you can open it later.

**Closed as completed by ShichenXie** 2021-05-23 14:36 UTC

**Comment by jm448** [comment] 2021-05-25 14:37
Hi @ShichenXie, thank you for your response. I was able to replicate your results using Ubuntu. I think that the difference must be due to some decimal criteria on windows.

``` r

library(readr)
library(scorecard)
#> Warning: package 'scorecard' was built under R version 4.0.5
suppressPackageStartupMessages(library(dplyr))

sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Spanish_Chile.1252  LC_CTYPE=Spanish_Chile.1252   
#> [3] LC_MONETARY=Spanish_Chile.1252 LC_NUMERIC=C                  
#> [5] LC_TIME=Spanish_Chile.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dplyr_1.0.2     scorecard_0.3.2 readr_1.4.0    
#> 
#> loaded via a namespace (and not attached):
#>  [1] zip_2.1.1         Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.3   
#>  [5] highr_0.8         iterators_1.0.13  tools_4.0.3       digest_0.6.27    
#>  [9] evaluate_0.14     lifecycle_0.2.0   tibble_3.0.4      gtable_0.3.0     
#> [13] pkgconfig_2.0.3   rlang_0.4.8       openxlsx_4.2.2    foreach_1.5.1    
#> [17] parallel_4.0.3    yaml_2.2.1        xfun_0.18         gridExtra_2.3    
#> [21] stringr_1.4.0     knitr_1.30        generics_0.0.2    vctrs_0.3.4      
#> [25] hms_0.5.3         grid_4.0.3        tidyselect_1.1.0  glue_1.4.2       
#> [29] data.table_1.13.2 R6_2.5.0          rmarkdown_2.5     ggplot2_3.3.2    
#> [33] purrr_0.3.4       magrittr_1.5      scales_1.1.1      codetools_0.2-16 
#> [37] ellipsis_0.3.1    htmltools_0.5.0   colorspace_1.4-1  stringi_1.5.3    
#> [41] doParallel_1.0.16 munsell_0.5.0     crayon_1.3.4

packageVersion("scorecard")
#> [1] '0.3.2'

d <- read_csv("https://gist.githubusercontent.com/jm448/a8edc0f3a89c6797c52aa84f978eca6f/raw/4ca39c576a23ae5b94b19c5829149d6800b75991/data.txt")
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   x = col_double(),
#>   response = col_double()
#> )

glimpse(d)
#> Rows: 253
#> Columns: 2
#> $ x        <dbl> 1.0000000, -999.0000000, 0.3639344, 0.9988413, 0.7696078, ...
#> $ response <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...

bin <- woebin(
  d, 
  x = "x",
  y = "response",
  method = "tree",
  count_distr_limit = 0.05 
)
#> [INFO] creating woe binning ...

bin
#> $x
#>    variable        bin count count_distr neg pos    posprob         woe
#> 1:        x   [-Inf,0)    24  0.09486166  15   9 0.37500000  1.16158709
#> 2:        x   [0,0.52)    88  0.34782609  80   8 0.09090909 -0.63017238
#> 3:        x [0.52,0.6)    21  0.08300395  16   5 0.23809524  0.50926190
#> 4:        x [0.6, Inf)   120  0.47430830 102  18 0.15000000 -0.06218834
#>         bin_iv  total_iv breaks is_special_values
#> 1: 0.179555187 0.3174041      0             FALSE
#> 2: 0.110649986 0.3174041   0.52             FALSE
#> 3: 0.025403323 0.3174041    0.6             FALSE
#> 4: 0.001795579 0.3174041    Inf             FALSE

# counts:

bin$x$count
#> [1]  24  88  21 120

brks <- bin$x$breaks
brks <- as.numeric(brks)
brks <- c(-Inf, brks)

brks
#> [1] -Inf 0.00 0.52 0.60  Inf

dc <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin)

dc
#> # A tibble: 4 x 2
#>   x_bin          n
#>   <fct>      <int>
#> 1 [-Inf,0)      24
#> 2 [0,0.52)      88
#> 3 [0.52,0.6)    20
#> 4 [0.6, Inf)   121

# the counts using cut doesn't match with the woebin results  

dc$n
#> [1]  24  88  20 121

# the counts match using woebin_ply

woebin_ply(d, bins = bin, to = "bin") %>%
  as_tibble() %>% 
  mutate(
    x = d$x,
    x_bin2 = cut(x, brks, right = FALSE)
  ) %>% 
  filter(x_bin != x_bin2)
#> [INFO] converting into woe values ...
#> # A tibble: 0 x 4
#> # ... with 4 variables: response <dbl>, x_bin <chr>, x <dbl>, x_bin2 <fct>

# the woe values match

bin$x %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(bin, count, pos, neg, woe, woe2) %>% 
  mutate(woe == woe2)
#>           bin count pos neg         woe        woe2 woe == woe2
#> 1:   [-Inf,0)    24   9  15  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52)    88   8  80 -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)    21   5  16  0.50926190  0.50926190        TRUE
#> 4: [0.6, Inf)   120  18 102 -0.06218834 -0.06218834        TRUE

# woe values using base::cut

bin2 <- d %>% 
  mutate(x_bin = cut(x, brks, right = FALSE)) %>% 
  count(x_bin, response) %>% 
  mutate(response = if_else(response == 1, "pos", "neg")) %>% 
  tidyr::pivot_wider(names_from = "response", values_from = "n") %>% 
  mutate(
    neg_porc = neg / sum(neg),
    pos_porc = pos / sum(pos),
    woe2 = log(pos_porc / neg_porc)
  ) %>% 
  select(x_bin, woe2)
  
# the woe values using base::cut doesn't match with woe values from woebin

bin$x %>% 
  select(bin, woe) %>% 
  left_join(bin2, by = c("bin" = "x_bin")) %>% 
  mutate(woe == woe2)
#>           bin         woe        woe2 woe == woe2
#> 1:   [-Inf,0)  1.16158709  1.16158709        TRUE
#> 2:   [0,0.52) -0.63017238 -0.63017238        TRUE
#> 3: [0.52,0.6)  0.50926190  0.57380042       FALSE
#> 4: [0.6, Inf) -0.06218834 -0.07194452       FALSE
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
