### ISSUE TITLE
chimerge error

### ISSUE THREAD

**Issue by stellalibre** [ShichenXie/scorecard#46] opened 2020-10-28 14:47 UTC
Running the woebin function with method = "chimerge" produces an error.
In addition, if I use the method = "tree" and set the bin_num_limit = 10, some of the variables still have more than 10 bins.

```
bins <- scorecard::woebin(dt = TrainingData, y= "StatusbinnenT12",
+                x =xvars,positive = 1, count_distr_limit = 0.01,
+                bin_num_limit = 10, method = "chimerge") 

```

Result:
[INFO] creating woe binning ... 
Error in checkForRemoteErrors(val) : 
  one node produced an error: Error in match.arg(type) : 'arg' must be NULL or a character vector

**Comment by ShichenXie** [comment] 2020-10-28 15:50
please provide a reproducible data set.

**Comment by ShichenXie** [comment] 2020-11-05 12:26
Since I cant reproduce your issue, I close it now.

**Closed as completed by ShichenXie** 2020-11-05 12:26 UTC
