### ISSUE TITLE
Package Not Available in R 3.4.1

### ISSUE THREAD

**Issue by MarkovCredit** [ShichenXie/scorecard#2] opened 2017-11-29 19:41 UTC
I cannot install this package in either R studio or Visual Studio with R Tools. THe package is supposedly "unavailable" ? Please advise.

Best,

ML

**Comment by ShichenXie** [comment] 2017-12-03 05:46
Thank you for interesting in this package.  You can install it from CRAN via `install.packages("scorecard")`. If you still can't install it, show me the error message.

**Comment by ShichenXie** [comment] 2017-12-05 07:42
Since this issue is a very basic question, I close it now.

**Closed as completed by ShichenXie** 2017-12-05 07:42 UTC

**Comment by MarkovCredit** [comment] 2017-12-05 15:36
The error is "this package is not available under R 3.4.1"

**Comment by ShichenXie** [comment] 2018-04-19 08:26
Did you still have this problem? I'm using the latest version of R. If you still can't install this package, try to update your R

**Comment by MarkovCredit** [comment] 2018-04-19 15:57
No, the package is working.

Thank you for checking!

Curious if there are any other algorithms that can be used in R for
scorecard like random Forest or SBG?

On Apr 19, 2018 4:26 AM, "Shichen" <notifications@github.com> wrote:

Did you still have this problem? I'm using the latest version of R. If you
still can't install this package, try to update your R

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ShichenXie/scorecard/issues/2#issuecomment-382653154>,
or mute the thread

**Comment by ShichenXie** [comment] 2018-04-20 08:31
Actually, scorecard is a model using woe values in logistic regression. Of course, you can use other algorithms with woe values as input dataset.

But, I don't know how woe transformation affects the model robustness. You can compare it with other data preprocessing in those algorithms.
